#!/bin/bash
# OpenTelemetry Collector Agent Installation Script
# Auto-generated by InternalPaaS Platform
# DO NOT MODIFY MANUALLY

set -e

# Configuration
INSTALL_DIR="/opt/metrics-agent"
SERVICE_NAME="otelcol"
CONFIG_FILE="$INSTALL_DIR/otelcol.yaml"
BINARY_FILE="$INSTALL_DIR/otelcol"
LOG_DIR="$INSTALL_DIR/logs"
TMP_DIR="/tmp/metrics-agent-install"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Error handler
error_exit() {
    log_error "$1"
    exit 1
}

echo "=================================================="
echo "  OpenTelemetry Collector Agent Installation"
echo "  Platform: InternalPaaS"
echo "  Version: 0.91.0"
echo "=================================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    log_warn "Running as root is not recommended"
fi

# Step 1: Create installation directory
log_info "[1/7] Creating installation directory..."
sudo mkdir -p "$INSTALL_DIR" || error_exit "Failed to create installation directory"
sudo mkdir -p "$LOG_DIR" || error_exit "Failed to create log directory"

# Change ownership to current user
sudo chown -R $(whoami):$(whoami) "$INSTALL_DIR" || log_warn "Failed to change ownership"

# Step 2: Check if agent binary exists
log_info "[2/7] Checking agent binary..."
if [ ! -f "$TMP_DIR/agent.tar.gz" ]; then
    error_exit "Agent binary not found at $TMP_DIR/agent.tar.gz"
fi

# Step 3: Extract agent binary
log_info "[3/7] Extracting agent binary..."
tar -xzf "$TMP_DIR/agent.tar.gz" -C "$INSTALL_DIR" || error_exit "Failed to extract agent binary"

# Make binary executable
chmod +x "$BINARY_FILE" || error_exit "Failed to make binary executable"

# Verify binary
if [ ! -x "$BINARY_FILE" ]; then
    error_exit "Binary file is not executable"
fi

log_info "Agent binary extracted successfully"

# Step 4: Copy configuration file
log_info "[4/7] Configuring agent..."
if [ ! -f "$TMP_DIR/otelcol.yaml" ]; then
    error_exit "Configuration file not found at $TMP_DIR/otelcol.yaml"
fi

cp "$TMP_DIR/otelcol.yaml" "$CONFIG_FILE" || error_exit "Failed to copy configuration file"
chmod 644 "$CONFIG_FILE" || log_warn "Failed to set configuration file permissions"

log_info "Configuration copied successfully"

# Step 5: Create systemd service
log_info "[5/7] Creating systemd service..."

sudo tee /etc/systemd/system/$SERVICE_NAME.service > /dev/null <<EOF || error_exit "Failed to create systemd service"
[Unit]
Description=OpenTelemetry Collector Agent
Documentation=https://opentelemetry.io/docs/collector/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$(whoami)
Group=$(whoami)
WorkingDirectory=$INSTALL_DIR
ExecStart=$BINARY_FILE --config=$CONFIG_FILE
Restart=on-failure
RestartSec=5s
StandardOutput=append:$LOG_DIR/otelcol.log
StandardError=append:$LOG_DIR/otelcol-error.log

# Security
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$INSTALL_DIR

# Resource limits
LimitNOFILE=8192
LimitNPROC=512

[Install]
WantedBy=multi-user.target
EOF

log_info "Systemd service created successfully"

# Step 6: Reload systemd and enable service
log_info "[6/7] Enabling and starting service..."

sudo systemctl daemon-reload || error_exit "Failed to reload systemd"
sudo systemctl enable $SERVICE_NAME || error_exit "Failed to enable service"
sudo systemctl start $SERVICE_NAME || error_exit "Failed to start service"

log_info "Service enabled and started"

# Step 7: Verify installation
log_info "[7/7] Verifying installation..."

# Wait for service to stabilize
sleep 3

# Check service status
if sudo systemctl is-active --quiet $SERVICE_NAME; then
    log_info "✅ Service is running"
else
    log_error "Service is not running"
    sudo systemctl status $SERVICE_NAME --no-pager
    error_exit "Service failed to start"
fi

# Check if process exists
if pgrep -f "$BINARY_FILE" > /dev/null; then
    log_info "✅ Process is running"
else
    log_warn "Process check failed (but service is active)"
fi

# Check if ports are listening (4317 for gRPC, 4318 for HTTP)
# Note: Agent doesn't listen on these ports in receiver mode, only in gateway mode
# This check is optional

# Step 8: Cleanup
log_info "Cleaning up temporary files..."
rm -rf "$TMP_DIR" || log_warn "Failed to cleanup temporary files"

# Final status
echo ""
echo "=================================================="
echo -e "${GREEN}✅ Installation completed successfully!${NC}"
echo "=================================================="
echo ""
echo "Service Status:"
sudo systemctl status $SERVICE_NAME --no-pager --lines=0
echo ""
echo "Useful Commands:"
echo "  - View status:  sudo systemctl status $SERVICE_NAME"
echo "  - View logs:    sudo journalctl -u $SERVICE_NAME -f"
echo "  - Restart:      sudo systemctl restart $SERVICE_NAME"
echo "  - Stop:         sudo systemctl stop $SERVICE_NAME"
echo "  - Logs dir:     $LOG_DIR"
echo ""

exit 0
