/**
 * Authentication Type Definitions
 *
 * Type definitions for JWT tokens, user identity, and authentication state.
 */

/**
 * JWT Access Token structure
 * Generated by BFF (Backend-for-Frontend) and stored in memory
 */
export interface Token {
  /**
   * JWT string (header.payload.signature)
   * @example "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
   */
  accessToken: string;

  /**
   * Token expiration timestamp in milliseconds (Unix epoch)
   * @example 1738324800000 (2025-01-31 12:00:00 UTC)
   */
  expiresAt: number;

  /**
   * Token issuer (who signed the token)
   * @default "internalpaas"
   */
  issuer: string;

  /**
   * Intended audience (who should accept the token)
   * @default "deploy-platform"
   */
  audience: string;
}

/**
 * User identity information extracted from token
 */
export interface User {
  /**
   * Unique username (from JWT 'sub' claim)
   * @example "admin", "developer1"
   */
  username: string;

  /**
   * User role (from JWT 'role' claim)
   * @example "ADMIN", "DEVELOPER"
   */
  role: 'ADMIN' | 'DEVELOPER' | 'SUPER_ADMIN';
}

/**
 * Token refresh request payload
 */
export interface TokenRefreshRequest {
  /**
   * Current access token to be refreshed
   */
  currentToken: string;
}

/**
 * Token refresh response from BFF
 */
export interface TokenRefreshResponse {
  /**
   * New access token
   */
  accessToken: string;

  /**
   * New token expiration timestamp (Unix epoch in milliseconds)
   */
  expiresAt: number;
}
